const productArray = [
  {
    productId: "150284",
    productName: "Mueble despensero Dalia MDP 80x182cm Blanco",
    brand: "Orange",
    brandId: 949,
    brandImageUrl: null,
    linkText: "mueble-despensero-dalia-mdp-80-cm-blanco",
    productReference: "150284",
    productReferenceCode: "150284",
    categoryId: "774",
    productTitle: "Mueble despensero Dalia MDP 80x182cm Blanco",
    metaTagDescription:
      "Compra online el Mueble despensero Dalia MDP 80x182cm Blanco en Promart.pe ¡Ingresa Aquí!",
    releaseDate: "2023-06-08T00:00:00Z",
    clusterHighlights: {
      "2459": "aniversario 20",
      "2864": "HP-IntegracionDespacho24horas-b",
      "3896": "Mostrar descuento",
      "3964": "top-ventas",
    },
    productClusters: {
      "170": "Dia de la madre - coleccion general",
      "171": "Landing-Mama-decoracion",
      "460": "Flete-gratis",
      "1541": "flete-gratis",
      "1562": "Especial-papa-cocinero",
      "1566": "Especial-papa-hogareno",
      "1580": "Destacado papa",
      "1615": "muebles de cocina-renueva tu casa",
      "1646": "CYBER9-04-COCINA",
      "2012": "ariadna-product-feed",
      "2137": "CYBERHOME",
      "2281": "MiniCyber - almacena y mantén tus alimentos",
      "2331": "Land-Marca-Orange - mejores marcas",
      "2339": "Especial mamá 20 - chef",
      "2345": "Especial mamá 20 - genérico",
      "2374": "Cocinas y Baños",
      "2382": "Papá 20 - general",
      "2406": "Descuento - Baños y Cocinas",
      "2415": "Home Sale",
      "2459": "aniversario 20",
      "2661": "Landing Tarjeta oh! - Muebles",
      "2662": "Landing Tarjeta oh! - Cocina",
      "2778": "Landing OH Automatizada",
      "2788": "CyberWow-Cocinas",
      "2864": "HP-IntegracionDespacho24horas-b",
      "2879": "Cyber-Promart",
      "2887": "aniversario20 - cocina",
      "3040": "Cyber - Los mas vendidos",
      "3256": "Envio gratis - categorias",
      "3523": "Search-Muebles de cocina",
      "3817": "Search-Armario",
      "3896": "Mostrar descuento",
      "3964": "top-ventas",
      "4057": "tag-1-generico",
      "4333": "ExclusionTodocyberPromart",
      "4341": "Promo exclusionblackweekend",
      "4357": "fletes-gratis-TAG",
      "4468": "Aire libre, orga, jardin-flete",
      "4499": "Flete Gratis - Colección",
      "4553": "CSI Segmentado",
      "4577": "Envio Gratis Cocinas",
      "4589": "CSI Segmentado",
    },
    searchableClusters: {},
    categories: [
      "/Cocina/Muebles de cocina/Alacenas y muebles para microondas/",
      "/Cocina/Muebles de cocina/",
      "/Cocina/",
    ],
    categoriesIds: ["/688/700/774/", "/688/700/", "/688/"],
    link: "https://www.promart.pe/mueble-despensero-dalia-mdp-80-cm-blanco/p",
    Promociones: ["Tarjeta oh!", "Envío gratis"],
    "Vendido por": ["Promart"],
    Atributos: ["Promociones", "Vendido por"],
    Características: ["Excelente calidad. Resistencia y durabilidad."],
    Garantía: ["1 Año"],
    "Profundidad Del Producto": ["40 cm"],
    "Recomendaciones De Uso": ["Limpiar con un paño seco o húmedo."],
    "Altura Del Producto": ["182 cm"],
    "Tipo de estructura": ["Fijo"],
    Modelo: ["Para cocina"],
    "Tipo de Producto": ["Mueble de Cocina"],
    "Ancho Del Producto": ["80 cm"],
    "Sub Tipo de Producto": ["Despensero"],
    Material: ["MDP"],
    Color: ["Blanco"],
    Marca: ["Orange"],
    "Número de puertas": ["2"],
    "Peso Del Producto": ["48.5 kg"],
    "Material de puertas": ["MDP"],
    Ventajas: ["Utilidad y organización a su alcance."],
    "Advertencia de uso": [
      "Para uso residencial. No exponer a sol y humedad excesiva. Evitar el contacto prolongado con líquidos. No limpiar con material abrasivo. No es necesario el uso de abrillantador y/o cera para su mantenimiento.",
    ],
    "Material de Base": ["MDP"],
    "Tipo de uso": ["Doméstico/Interior"],
    Uso: ["Para la organización de alimentos."],
    "¿Dónde usarlo?": ["En área de la cocina."],
    "Ficha Técnica": [
      "Características",
      "Garantía",
      "Profundidad Del Producto",
      "Recomendaciones De Uso",
      "Altura Del Producto",
      "Tipo de estructura",
      "Modelo",
      "Tipo de Producto",
      "Ancho Del Producto",
      "Sub Tipo de Producto",
      "Material",
      "Color",
      "Marca",
      "Número de puertas",
      "Peso Del Producto",
      "Material de puertas",
      "Ventajas",
      "Advertencia de uso",
      "Material de Base",
      "Tipo de uso",
      "Uso",
      "¿Dónde usarlo?",
    ],
    DescriptionBrand: [
      "<p>&bull; Ideal para organizar alimentos, utensilios o art&iacute;culos de despensa.<br />\r\n&bull; Fabricado en MDP de gran durabilidad.<br />\r\n&bull; Acabado blanco que aporta luminosidad y amplitud.</p>",
    ],
    Interno: ["DescriptionBrand"],
    allSpecifications: [
      "Promociones",
      "Vendido por",
      "Características",
      "Garantía",
      "Profundidad Del Producto",
      "Recomendaciones De Uso",
      "Altura Del Producto",
      "Tipo de estructura",
      "Modelo",
      "Tipo de Producto",
      "Ancho Del Producto",
      "Sub Tipo de Producto",
      "Material",
      "Color",
      "Marca",
      "Número de puertas",
      "Peso Del Producto",
      "Material de puertas",
      "Ventajas",
      "Advertencia de uso",
      "Material de Base",
      "Tipo de uso",
      "Uso",
      "¿Dónde usarlo?",
      "DescriptionBrand",
    ],
    allSpecificationsGroups: ["Atributos", "Ficha Técnica", "Interno"],
    description:
      "Excelente calidad. Resistencia y durabilidad. Disfruta de lo más nuevo que Promart.pe trae para ti.",
    items: [
      {
        itemId: "150284",
        name: "Mueble despensero Dalia MDP 80x182cm Blanco",
        nameComplete: "Mueble despensero Dalia MDP 80x182cm Blanco",
        complementName: "Mueble despensero Dalia MDP 80x182cm Blanco",
        ean: "7899467137779",
        referenceId: [
          {
            Key: "RefId",
            Value: "150284",
          },
        ],
        measurementUnit: "un",
        unitMultiplier: 1.0,
        modalType: null,
        isKit: false,
        images: [
          {
            imageId: "7829690",
            imageLabel: null,
            imageTag:
              '<img src="~/arquivos/ids/7829690-#width#-#height#/150284.jpg?v=638424797532970000" width="#width#" height="#height#" alt="150284" id="" />',
            imageUrl:
              "https://promart.vteximg.com.br/arquivos/ids/7829690/150284.jpg?v=638424797532970000",
            imageText: "150284",
            imageLastModified: "2024-02-02T14:09:13.2970000Z",
          },
          {
            imageId: "7829691",
            imageLabel: null,
            imageTag:
              '<img src="~/arquivos/ids/7829691-#width#-#height#/150284_0.jpg?v=638424797536400000" width="#width#" height="#height#" alt="150284_0" id="" />',
            imageUrl:
              "https://promart.vteximg.com.br/arquivos/ids/7829691/150284_0.jpg?v=638424797536400000",
            imageText: "150284_0",
            imageLastModified: "2024-02-02T14:09:13.6400000Z",
          },
          {
            imageId: "7829692",
            imageLabel: null,
            imageTag:
              '<img src="~/arquivos/ids/7829692-#width#-#height#/150284_1.jpg?v=638424797539370000" width="#width#" height="#height#" alt="150284_1" id="" />',
            imageUrl:
              "https://promart.vteximg.com.br/arquivos/ids/7829692/150284_1.jpg?v=638424797539370000",
            imageText: "150284_1",
            imageLastModified: "2024-02-02T14:09:13.9370000Z",
          },
          {
            imageId: "7829693",
            imageLabel: null,
            imageTag:
              '<img src="~/arquivos/ids/7829693-#width#-#height#/150284_10.jpg?v=638424797542870000" width="#width#" height="#height#" alt="150284_10" id="" />',
            imageUrl:
              "https://promart.vteximg.com.br/arquivos/ids/7829693/150284_10.jpg?v=638424797542870000",
            imageText: "150284_10",
            imageLastModified: "2024-02-02T14:09:14.2870000Z",
          },
          {
            imageId: "7829694",
            imageLabel: null,
            imageTag:
              '<img src="~/arquivos/ids/7829694-#width#-#height#/150284_20.jpg?v=638424797545270000" width="#width#" height="#height#" alt="150284_20" id="" />',
            imageUrl:
              "https://promart.vteximg.com.br/arquivos/ids/7829694/150284_20.jpg?v=638424797545270000",
            imageText: "150284_20",
            imageLastModified: "2024-02-02T14:09:14.5270000Z",
          },
          {
            imageId: "7829695",
            imageLabel: null,
            imageTag:
              '<img src="~/arquivos/ids/7829695-#width#-#height#/150284_21.jpg?v=638424797548700000" width="#width#" height="#height#" alt="150284_21" id="" />',
            imageUrl:
              "https://promart.vteximg.com.br/arquivos/ids/7829695/150284_21.jpg?v=638424797548700000",
            imageText: "150284_21",
            imageLastModified: "2024-02-02T14:09:14.8700000Z",
          },
          {
            imageId: "7829696",
            imageLabel: null,
            imageTag:
              '<img src="~/arquivos/ids/7829696-#width#-#height#/150284_80.jpg?v=638424797551400000" width="#width#" height="#height#" alt="150284_80" id="" />',
            imageUrl:
              "https://promart.vteximg.com.br/arquivos/ids/7829696/150284_80.jpg?v=638424797551400000",
            imageText: "150284_80",
            imageLastModified: "2024-02-02T14:09:15.1400000Z",
          },
        ],
        sellers: [
          {
            sellerId: "1",
            sellerName: "Promart",
            addToCartLink:
              "https://www.promart.pe/checkout/cart/add?sku=150284&qty=1&seller=1&sc=2&price=30900&cv=_&sc=2",
            sellerDefault: true,
            commertialOffer: {
              DeliverySlaSamplesPerRegion: {
                "0": {
                  DeliverySlaPerTypes: [],
                  Region: null,
                },
              },
              Installments: [
                {
                  Value: 309.0,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 309.0,
                  NumberOfInstallments: 1,
                  PaymentSystemName: "AGORAWEB",
                  PaymentSystemGroupName: "custom201PaymentGroupPaymentGroup",
                  Name: "AGORAWEB à vista",
                },
                {
                  Value: 309.0,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 309.0,
                  NumberOfInstallments: 1,
                  PaymentSystemName: "Tarjeta-Oh-Cuotas",
                  PaymentSystemGroupName: "custom203PaymentGroupPaymentGroup",
                  Name: "Tarjeta-Oh-Cuotas à vista",
                },
                {
                  Value: 309.0,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 309.0,
                  NumberOfInstallments: 1,
                  PaymentSystemName: "Tarjetas-Credito-Debito-PROM",
                  PaymentSystemGroupName: "custom206PaymentGroupPaymentGroup",
                  Name: "Tarjetas-Credito-Debito-PROM à vista",
                },
                {
                  Value: 309.0,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 309.0,
                  NumberOfInstallments: 1,
                  PaymentSystemName: "Agora-Visa",
                  PaymentSystemGroupName: "custom208PaymentGroupPaymentGroup",
                  Name: "Agora-Visa à vista",
                },
                {
                  Value: 309.0,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 309.0,
                  NumberOfInstallments: 1,
                  PaymentSystemName: "Tarjetas-INTERBANK",
                  PaymentSystemGroupName: "custom209PaymentGroupPaymentGroup",
                  Name: "Tarjetas-INTERBANK à vista",
                },
              ],
              DiscountHighLight: [],
              GiftSkuIds: [],
              Teasers: [
                {
                  "<Name>k__BackingField": "OH- TP517",
                  "<GeneralValues>k__BackingField": {},
                  "<Conditions>k__BackingField": {
                    "<MinimumQuantity>k__BackingField": 0,
                    "<Parameters>k__BackingField": [
                      {
                        "<Name>k__BackingField": "PaymentMethodId",
                        "<Value>k__BackingField": "203",
                      },
                    ],
                  },
                  "<Effects>k__BackingField": {
                    "<Parameters>k__BackingField": [
                      {
                        "<Name>k__BackingField":
                          "PromotionalPriceTableItemsIds",
                        "<Value>k__BackingField": "150284",
                      },
                      {
                        "<Name>k__BackingField":
                          "PromotionalPriceTableItemsDiscount",
                        "<Value>k__BackingField": "40.00",
                      },
                    ],
                  },
                },
              ],
              PromotionTeasers: [
                {
                  Name: "OH- TP517",
                  GeneralValues: {},
                  Conditions: {
                    MinimumQuantity: 0,
                    Parameters: [
                      {
                        Name: "PaymentMethodId",
                        Value: "203",
                      },
                    ],
                  },
                  Effects: {
                    Parameters: [
                      {
                        Name: "PromotionalPriceTableItemsIds",
                        Value: "150284",
                      },
                      {
                        Name: "PromotionalPriceTableItemsDiscount",
                        Value: "40.00",
                      },
                    ],
                  },
                },
              ],
              BuyTogether: [],
              ItemMetadataAttachment: [],
              Price: 309.0,
              ListPrice: 369.0,
              PriceWithoutDiscount: 309.0,
              FullSellingPrice: 309.0,
              RewardValue: 0.0,
              PriceValidUntil: "2024-03-28T00:00:00Z",
              AvailableQuantity: 364,
              IsAvailable: true,
              Tax: 0.0,
              DeliverySlaSamples: [
                {
                  DeliverySlaPerTypes: [],
                  Region: null,
                },
              ],
              GetInfoErrorMessage: null,
              CacheVersionUsedToCallCheckout: "_",
              PaymentOptions: {
                installmentOptions: [
                  {
                    paymentSystem: "201",
                    bin: null,
                    paymentName: "AGORAWEB",
                    paymentGroupName: "custom201PaymentGroupPaymentGroup",
                    value: 30900,
                    installments: [
                      {
                        count: 1,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 30900,
                        total: 30900,
                        sellerMerchantInstallments: [
                          {
                            id: "PROMARTTEST",
                            count: 1,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 30900,
                            total: 30900,
                          },
                        ],
                      },
                    ],
                  },
                  {
                    paymentSystem: "203",
                    bin: null,
                    paymentName: "Tarjeta-Oh-Cuotas",
                    paymentGroupName: "custom203PaymentGroupPaymentGroup",
                    value: 30900,
                    installments: [
                      {
                        count: 1,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 30900,
                        total: 30900,
                        sellerMerchantInstallments: [
                          {
                            id: "PROMARTTEST",
                            count: 1,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 30900,
                            total: 30900,
                          },
                        ],
                      },
                    ],
                  },
                  {
                    paymentSystem: "206",
                    bin: null,
                    paymentName: "Tarjetas-Credito-Debito-PROM",
                    paymentGroupName: "custom206PaymentGroupPaymentGroup",
                    value: 30900,
                    installments: [
                      {
                        count: 1,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 30900,
                        total: 30900,
                        sellerMerchantInstallments: [
                          {
                            id: "PROMARTTEST",
                            count: 1,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 30900,
                            total: 30900,
                          },
                        ],
                      },
                    ],
                  },
                  {
                    paymentSystem: "208",
                    bin: null,
                    paymentName: "Agora-Visa",
                    paymentGroupName: "custom208PaymentGroupPaymentGroup",
                    value: 30900,
                    installments: [
                      {
                        count: 1,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 30900,
                        total: 30900,
                        sellerMerchantInstallments: [
                          {
                            id: "PROMARTTEST",
                            count: 1,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 30900,
                            total: 30900,
                          },
                        ],
                      },
                    ],
                  },
                  {
                    paymentSystem: "209",
                    bin: null,
                    paymentName: "Tarjetas-INTERBANK",
                    paymentGroupName: "custom209PaymentGroupPaymentGroup",
                    value: 30900,
                    installments: [
                      {
                        count: 1,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 30900,
                        total: 30900,
                        sellerMerchantInstallments: [
                          {
                            id: "PROMARTTEST",
                            count: 1,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 30900,
                            total: 30900,
                          },
                        ],
                      },
                    ],
                  },
                ],
                paymentSystems: [
                  {
                    id: 201,
                    name: "AGORAWEB",
                    groupName: "custom201PaymentGroupPaymentGroup",
                    validator: null,
                    stringId: "201",
                    template: "custom201PaymentGroupPaymentGroup-template",
                    requiresDocument: false,
                    isCustom: true,
                    description: "AGORAWEB",
                    requiresAuthentication: false,
                    dueDate: "2024-03-14T18:00:00Z",
                    availablePayments: null,
                  },
                  {
                    id: 209,
                    name: "Tarjetas-INTERBANK",
                    groupName: "custom209PaymentGroupPaymentGroup",
                    validator: null,
                    stringId: "209",
                    template: "custom209PaymentGroupPaymentGroup-template",
                    requiresDocument: false,
                    isCustom: true,
                    description: "Tarjetas de Interbank",
                    requiresAuthentication: false,
                    dueDate: "2024-03-13T18:00:00Z",
                    availablePayments: null,
                  },
                  {
                    id: 208,
                    name: "Agora-Visa",
                    groupName: "custom208PaymentGroupPaymentGroup",
                    validator: null,
                    stringId: "208",
                    template: "custom208PaymentGroupPaymentGroup-template",
                    requiresDocument: false,
                    isCustom: true,
                    description: "Tarjeta Agora Visa",
                    requiresAuthentication: false,
                    dueDate: "2024-03-13T18:00:00Z",
                    availablePayments: null,
                  },
                  {
                    id: 203,
                    name: "Tarjeta-Oh-Cuotas",
                    groupName: "custom203PaymentGroupPaymentGroup",
                    validator: null,
                    stringId: "203",
                    template: "custom203PaymentGroupPaymentGroup-template",
                    requiresDocument: false,
                    isCustom: true,
                    description: "Tarjeta-Oh-Cuotas",
                    requiresAuthentication: false,
                    dueDate: "2024-03-13T18:00:00Z",
                    availablePayments: null,
                  },
                  {
                    id: 206,
                    name: "Tarjetas-Credito-Debito-PROM",
                    groupName: "custom206PaymentGroupPaymentGroup",
                    validator: null,
                    stringId: "206",
                    template: "custom206PaymentGroupPaymentGroup-template",
                    requiresDocument: false,
                    isCustom: true,
                    description: "Tarjetas-Credito-Debito-PROM",
                    requiresAuthentication: false,
                    dueDate: "2024-03-13T18:00:00Z",
                    availablePayments: null,
                  },
                ],
                payments: [],
                giftCards: [],
                giftCardMessages: [],
                availableAccounts: [],
                availableTokens: [],
              },
            },
          },
        ],
        Videos: [],
        estimatedDateArrival: null,
      },
    ],
  },
];
