const productsArray = [
  {
    productId: "2",
    productName: "Meow",
    brand: "Test Brand name",
    brandId: 2000000,
    brandImageUrl: null,
    linkText: "meow",
    productReference: "1234567",
    productReferenceCode: "1234567",
    categoryId: "1",
    productTitle: "Meow",
    metaTagDescription: "Produto teste da Karen",
    releaseDate: "2021-03-09T00:00:00Z",
    clusterHighlights: {
      "140": "Coleção teste da Karen e do Bruno",
    },
    productClusters: {
      "140": "Coleção teste da Karen e do Bruno",
    },
    searchableClusters: {
      "140": "Coleção teste da Karen e do Bruno",
    },
    categories: ["/Test Category/"],
    categoriesIds: ["/1/"],
    link: "https://apiexamples.vtexcommercestable.com.br/meow/p",
    description: "Produto teste da Karen",
    items: [
      {
        itemId: "2",
        name: "Meow SKU",
        nameComplete: "Meow SKU",
        complementName: "",
        ean: "09877654321",
        referenceId: [
          {
            Key: "RefId",
            Value: "1234567",
          },
        ],
        measurementUnit: "un",
        unitMultiplier: 1,
        modalType: null,
        isKit: false,
        images: [
          {
            imageId: "155398",
            imageLabel: "miau",
            imageTag:
              '<img src="~/arquivos/ids/155398-#width#-#height#/Cat-Sleeping-Pics.jpg?v=637509163299000000" width="#width#" height="#height#" alt="gatenho" id="" />',
            imageUrl:
              "https://apiexamples.vteximg.com.br/arquivos/ids/155398/Cat-Sleeping-Pics.jpg?v=637509163299000000",
            imageText: "gatenho",
            imageLastModified: "2021-03-09T19:52:09.9000000Z",
          },
        ],
        sellers: [
          {
            sellerId: "1",
            sellerName: "UNISUPER, SOCIEDAD ANONIMA",
            addToCartLink:
              "https://apiexamples.vtexcommercestable.com.br/checkout/cart/add?sku=2&qty=1&seller=1&sc=1&price=13000&cv=9F5DDDF45171475B97F6A2BEDED8C781_&sc=1",
            sellerDefault: true,
            commertialOffer: {
              DeliverySlaSamplesPerRegion: {
                "0": {
                  DeliverySlaPerTypes: [],
                  Region: null,
                },
              },
              Installments: [
                {
                  Value: 130,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 130,
                  NumberOfInstallments: 1,
                  PaymentSystemName: "Visa",
                  PaymentSystemGroupName: "creditCardPaymentGroup",
                  Name: "Visa à vista",
                },
                {
                  Value: 130,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 130,
                  NumberOfInstallments: 1,
                  PaymentSystemName: "Promissory",
                  PaymentSystemGroupName: "custom201PaymentGroupPaymentGroup",
                  Name: "Promissory à vista",
                },
              ],
              DiscountHighLight: [],
              GiftSkuIds: [],
              Teasers: [],
              PromotionTeasers: [],
              BuyTogether: [],
              ItemMetadataAttachment: [],
              Price: 130,
              ListPrice: 130,
              PriceWithoutDiscount: 130,
              FullSellingPrice: 130,
              RewardValue: 0,
              PriceValidUntil: "2025-03-11T15:58:30Z",
              AvailableQuantity: 200,
              IsAvailable: true,
              Tax: 0,
              DeliverySlaSamples: [
                {
                  DeliverySlaPerTypes: [],
                  Region: null,
                },
              ],
              GetInfoErrorMessage: null,
              CacheVersionUsedToCallCheckout:
                "9F5DDDF45171475B97F6A2BEDED8C781_",
              PaymentOptions: {
                installmentOptions: [
                  {
                    paymentSystem: "2",
                    bin: null,
                    paymentName: "Visa",
                    paymentGroupName: "creditCardPaymentGroup",
                    value: 13000,
                    installments: [
                      {
                        count: 1,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 13000,
                        total: 13000,
                        sellerMerchantInstallments: [
                          {
                            id: "APIEXAMPLES",
                            count: 1,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 13000,
                            total: 13000,
                          },
                        ],
                      },
                    ],
                  },
                  {
                    paymentSystem: "201",
                    bin: null,
                    paymentName: "Promissory",
                    paymentGroupName: "custom201PaymentGroupPaymentGroup",
                    value: 13000,
                    installments: [
                      {
                        count: 1,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 13000,
                        total: 13000,
                        sellerMerchantInstallments: [
                          {
                            id: "APIEXAMPLES",
                            count: 1,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 13000,
                            total: 13000,
                          },
                        ],
                      },
                    ],
                  },
                ],
                paymentSystems: [
                  {
                    id: 201,
                    name: "Promissory",
                    groupName: "custom201PaymentGroupPaymentGroup",
                    validator: null,
                    stringId: "201",
                    template: "custom201PaymentGroupPaymentGroup-template",
                    requiresDocument: false,
                    isCustom: true,
                    description: "Promissory Description",
                    requiresAuthentication: false,
                    dueDate: "2024-03-18T15:58:31.1629088Z",
                    availablePayments: null,
                  },
                  {
                    id: 2,
                    name: "Visa",
                    groupName: "creditCardPaymentGroup",
                    validator: null,
                    stringId: "2",
                    template: "creditCardPaymentGroup-template",
                    requiresDocument: false,
                    isCustom: false,
                    description: null,
                    requiresAuthentication: false,
                    dueDate: "2024-03-18T15:57:31.1629088Z",
                    availablePayments: null,
                  },
                ],
                payments: [],
                giftCards: [],
                giftCardMessages: [],
                availableAccounts: [],
                availableTokens: [],
              },
            },
          },
        ],
        Videos: [],
        estimatedDateArrival: null,
      },
    ],
  },
  {
    productId: "41",
    productName: "2020 AMACSA PH390",
    brand: "Brand",
    brandId: 9280,
    brandImageUrl: null,
    linkText: "2020-amacsa-ph390",
    productReference: "880035",
    productReferenceCode: "880035",
    categoryId: "9284",
    productTitle: "2020 AMACSA PH390",
    metaTagDescription: "Agricultural boom for giant and roll bales",
    releaseDate: "2020-01-01T00:00:00Z",
    clusterHighlights: {},
    productClusters: {
      "137": "All",
    },
    searchableClusters: {
      "137": "All",
    },
    categories: ["/Agribusiness/"],
    categoriesIds: ["/9284/"],
    link: "https://apiexamples.vtexcommercestable.com.br/2020-amacsa-ph390/p",
    description: "Agricultural boom for giant and roll bales",
    items: [
      {
        itemId: "70",
        name: "2020 AMACSA PH390",
        nameComplete: "2020 AMACSA PH390",
        complementName: "Agricultural boom for giant and roll bales",
        ean: "",
        referenceId: [
          {
            Key: "RefId",
            Value: "880350a",
          },
        ],
        measurementUnit: "un",
        unitMultiplier: 1,
        modalType: null,
        isKit: false,
        images: [
          {
            imageId: "155466",
            imageLabel: "2020-amacsa-ph390",
            imageTag:
              '<img src="~/arquivos/ids/155466-#width#-#height#/2020-amacsa-ph390.jpg?v=637534168300570000" width="#width#" height="#height#" alt="2020-amacsa-ph390" id="" />',
            imageUrl:
              "https://apiexamples.vteximg.com.br/arquivos/ids/155466/2020-amacsa-ph390.jpg?v=637534168300570000",
            imageText: "2020-amacsa-ph390",
            imageLastModified: "2021-04-07T18:27:10.0570000Z",
          },
        ],
        sellers: [
          {
            sellerId: "1",
            sellerName: "UNISUPER, SOCIEDAD ANONIMA",
            addToCartLink:
              "https://apiexamples.vtexcommercestable.com.br/checkout/cart/add?sku=70&qty=1&seller=1&sc=1&price=77500&cv=101E7710616A14A5A8C4C7ACCDD70471_&sc=1",
            sellerDefault: true,
            commertialOffer: {
              DeliverySlaSamplesPerRegion: {
                "0": {
                  DeliverySlaPerTypes: [],
                  Region: null,
                },
              },
              Installments: [
                {
                  Value: 775,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 775,
                  NumberOfInstallments: 1,
                  PaymentSystemName: "Visa",
                  PaymentSystemGroupName: "creditCardPaymentGroup",
                  Name: "Visa à vista",
                },
                {
                  Value: 775,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 775,
                  NumberOfInstallments: 1,
                  PaymentSystemName: "Promissory",
                  PaymentSystemGroupName: "custom201PaymentGroupPaymentGroup",
                  Name: "Promissory à vista",
                },
              ],
              DiscountHighLight: [],
              GiftSkuIds: [],
              Teasers: [],
              PromotionTeasers: [],
              BuyTogether: [],
              ItemMetadataAttachment: [],
              Price: 775,
              ListPrice: 3000,
              PriceWithoutDiscount: 775,
              FullSellingPrice: 775,
              RewardValue: 0,
              PriceValidUntil: "2025-03-11T15:58:30Z",
              AvailableQuantity: 1000000,
              IsAvailable: true,
              Tax: 0,
              DeliverySlaSamples: [
                {
                  DeliverySlaPerTypes: [],
                  Region: null,
                },
              ],
              GetInfoErrorMessage: null,
              CacheVersionUsedToCallCheckout:
                "101E7710616A14A5A8C4C7ACCDD70471_",
              PaymentOptions: {
                installmentOptions: [
                  {
                    paymentSystem: "2",
                    bin: null,
                    paymentName: "Visa",
                    paymentGroupName: "creditCardPaymentGroup",
                    value: 77500,
                    installments: [
                      {
                        count: 1,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 77500,
                        total: 77500,
                        sellerMerchantInstallments: [
                          {
                            id: "APIEXAMPLES",
                            count: 1,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 77500,
                            total: 77500,
                          },
                        ],
                      },
                    ],
                  },
                  {
                    paymentSystem: "201",
                    bin: null,
                    paymentName: "Promissory",
                    paymentGroupName: "custom201PaymentGroupPaymentGroup",
                    value: 77500,
                    installments: [
                      {
                        count: 1,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 77500,
                        total: 77500,
                        sellerMerchantInstallments: [
                          {
                            id: "APIEXAMPLES",
                            count: 1,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 77500,
                            total: 77500,
                          },
                        ],
                      },
                    ],
                  },
                ],
                paymentSystems: [
                  {
                    id: 201,
                    name: "Promissory",
                    groupName: "custom201PaymentGroupPaymentGroup",
                    validator: null,
                    stringId: "201",
                    template: "custom201PaymentGroupPaymentGroup-template",
                    requiresDocument: false,
                    isCustom: true,
                    description: "Promissory Description",
                    requiresAuthentication: false,
                    dueDate: "2024-03-18T15:58:31.1629088Z",
                    availablePayments: null,
                  },
                  {
                    id: 2,
                    name: "Visa",
                    groupName: "creditCardPaymentGroup",
                    validator: null,
                    stringId: "2",
                    template: "creditCardPaymentGroup-template",
                    requiresDocument: false,
                    isCustom: false,
                    description: null,
                    requiresAuthentication: false,
                    dueDate: "2024-03-18T15:57:31.1629088Z",
                    availablePayments: null,
                  },
                ],
                payments: [],
                giftCards: [],
                giftCardMessages: [],
                availableAccounts: [],
                availableTokens: [],
              },
            },
          },
        ],
        Videos: [],
        estimatedDateArrival: null,
      },
    ],
  },
  {
    productId: "40",
    productName: "Navel Oranges Grown Large Fresh Fruit",
    brand: "Brand",
    brandId: 9280,
    brandImageUrl: null,
    linkText: "navel-oranges-grown-large-fresh-fruit",
    productReference: "880032",
    productReferenceCode: "880032",
    categoryId: "9282",
    productTitle: "Navel Oranges Grown Large Fresh Fruit",
    metaTagDescription: "NAVEL ORANGES GROWN LARGE FRESH FRUIT",
    releaseDate: "2020-01-01T00:00:00Z",
    clusterHighlights: {},
    productClusters: {
      "137": "All",
      "138": "All",
      "139": "All",
    },
    searchableClusters: {
      "137": "All",
      "138": "All",
      "139": "All",
    },
    categories: ["/Food and beverage/"],
    categoriesIds: ["/9282/"],
    link: "https://apiexamples.vtexcommercestable.com.br/navel-oranges-grown-large-fresh-fruit/p",
    description: "NAVEL ORANGES GROWN LARGE FRESH FRUIT",
    items: [
      {
        itemId: "68",
        name: "Pack of 1",
        nameComplete: "Navel Oranges Grown Large Fresh Fruit Pack of 1",
        complementName: "NAVEL ORANGES GROWN LARGE FRESH FRUIT",
        ean: "",
        referenceId: [
          {
            Key: "RefId",
            Value: "880320a",
          },
        ],
        measurementUnit: "un",
        unitMultiplier: 1,
        modalType: null,
        isKit: false,
        images: [
          {
            imageId: "155464",
            imageLabel: "navel-oranges-grown-large-fresh",
            imageTag:
              '<img src="~/arquivos/ids/155464-#width#-#height#/navel-oranges-grown-large-fresh.jpg?v=637534167940900000" width="#width#" height="#height#" alt="navel-oranges-grown-large-fresh" id="" />',
            imageUrl:
              "https://apiexamples.vteximg.com.br/arquivos/ids/155464/navel-oranges-grown-large-fresh.jpg?v=637534167940900000",
            imageText: "navel-oranges-grown-large-fresh",
            imageLastModified: "2021-04-07T18:26:34.0900000Z",
          },
        ],
        sellers: [
          {
            sellerId: "1",
            sellerName: "UNISUPER, SOCIEDAD ANONIMA",
            addToCartLink:
              "https://apiexamples.vtexcommercestable.com.br/checkout/cart/add?sku=68&qty=1&seller=1&sc=1&price=10000&cv=C8D94BB7955AEF3714DB81F1A4B130EC_&sc=1",
            sellerDefault: true,
            commertialOffer: {
              DeliverySlaSamplesPerRegion: {
                "0": {
                  DeliverySlaPerTypes: [],
                  Region: null,
                },
              },
              Installments: [
                {
                  Value: 100,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 100,
                  NumberOfInstallments: 1,
                  PaymentSystemName: "Visa",
                  PaymentSystemGroupName: "creditCardPaymentGroup",
                  Name: "Visa à vista",
                },
                {
                  Value: 100,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 100,
                  NumberOfInstallments: 1,
                  PaymentSystemName: "Promissory",
                  PaymentSystemGroupName: "custom201PaymentGroupPaymentGroup",
                  Name: "Promissory à vista",
                },
              ],
              DiscountHighLight: [],
              GiftSkuIds: [],
              Teasers: [],
              PromotionTeasers: [],
              BuyTogether: [],
              ItemMetadataAttachment: [],
              Price: 100,
              ListPrice: 100,
              PriceWithoutDiscount: 100,
              FullSellingPrice: 100,
              RewardValue: 0,
              PriceValidUntil: "2025-03-11T15:58:30Z",
              AvailableQuantity: 1000000,
              IsAvailable: true,
              Tax: 0,
              DeliverySlaSamples: [
                {
                  DeliverySlaPerTypes: [],
                  Region: null,
                },
              ],
              GetInfoErrorMessage: null,
              CacheVersionUsedToCallCheckout:
                "C8D94BB7955AEF3714DB81F1A4B130EC_",
              PaymentOptions: {
                installmentOptions: [
                  {
                    paymentSystem: "2",
                    bin: null,
                    paymentName: "Visa",
                    paymentGroupName: "creditCardPaymentGroup",
                    value: 10000,
                    installments: [
                      {
                        count: 1,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 10000,
                        total: 10000,
                        sellerMerchantInstallments: [
                          {
                            id: "APIEXAMPLES",
                            count: 1,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 10000,
                            total: 10000,
                          },
                        ],
                      },
                    ],
                  },
                  {
                    paymentSystem: "201",
                    bin: null,
                    paymentName: "Promissory",
                    paymentGroupName: "custom201PaymentGroupPaymentGroup",
                    value: 10000,
                    installments: [
                      {
                        count: 1,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 10000,
                        total: 10000,
                        sellerMerchantInstallments: [
                          {
                            id: "APIEXAMPLES",
                            count: 1,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 10000,
                            total: 10000,
                          },
                        ],
                      },
                    ],
                  },
                ],
                paymentSystems: [
                  {
                    id: 201,
                    name: "Promissory",
                    groupName: "custom201PaymentGroupPaymentGroup",
                    validator: null,
                    stringId: "201",
                    template: "custom201PaymentGroupPaymentGroup-template",
                    requiresDocument: false,
                    isCustom: true,
                    description: "Promissory Description",
                    requiresAuthentication: false,
                    dueDate: "2024-03-18T15:58:31.1629088Z",
                    availablePayments: null,
                  },
                  {
                    id: 2,
                    name: "Visa",
                    groupName: "creditCardPaymentGroup",
                    validator: null,
                    stringId: "2",
                    template: "creditCardPaymentGroup-template",
                    requiresDocument: false,
                    isCustom: false,
                    description: null,
                    requiresAuthentication: false,
                    dueDate: "2024-03-18T15:57:31.1629088Z",
                    availablePayments: null,
                  },
                ],
                payments: [],
                giftCards: [],
                giftCardMessages: [],
                availableAccounts: [],
                availableTokens: [],
              },
            },
          },
        ],
        Videos: [],
        estimatedDateArrival: null,
      },
      {
        itemId: "69",
        name: "Pack of 12",
        nameComplete: "Navel Oranges Grown Large Fresh Fruit Pack of 12",
        complementName: "NAVEL ORANGES GROWN LARGE FRESH FRUIT",
        ean: "",
        referenceId: [
          {
            Key: "RefId",
            Value: "880321a",
          },
        ],
        measurementUnit: "un",
        unitMultiplier: 12,
        modalType: null,
        isKit: false,
        images: [
          {
            imageId: "155465",
            imageLabel: "navel-oranges-grown-large-fresh",
            imageTag:
              '<img src="~/arquivos/ids/155465-#width#-#height#/navel-oranges-grown-large-fresh.jpg?v=637534167941830000" width="#width#" height="#height#" alt="navel-oranges-grown-large-fresh" id="" />',
            imageUrl:
              "https://apiexamples.vteximg.com.br/arquivos/ids/155465/navel-oranges-grown-large-fresh.jpg?v=637534167941830000",
            imageText: "navel-oranges-grown-large-fresh",
            imageLastModified: "2021-04-07T18:26:34.1830000Z",
          },
        ],
        sellers: [
          {
            sellerId: "1",
            sellerName: "UNISUPER, SOCIEDAD ANONIMA",
            addToCartLink:
              "https://apiexamples.vtexcommercestable.com.br/checkout/cart/add?sku=69&qty=1&seller=1&sc=1&price=100000&cv=C8D94BB7955AEF3714DB81F1A4B130EC_&sc=1",
            sellerDefault: true,
            commertialOffer: {
              DeliverySlaSamplesPerRegion: {
                "0": {
                  DeliverySlaPerTypes: [],
                  Region: null,
                },
              },
              Installments: [
                {
                  Value: 1000,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 1000,
                  NumberOfInstallments: 1,
                  PaymentSystemName: "Visa",
                  PaymentSystemGroupName: "creditCardPaymentGroup",
                  Name: "Visa à vista",
                },
                {
                  Value: 1000,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 1000,
                  NumberOfInstallments: 1,
                  PaymentSystemName: "Promissory",
                  PaymentSystemGroupName: "custom201PaymentGroupPaymentGroup",
                  Name: "Promissory à vista",
                },
              ],
              DiscountHighLight: [],
              GiftSkuIds: [],
              Teasers: [],
              PromotionTeasers: [],
              BuyTogether: [],
              ItemMetadataAttachment: [],
              Price: 1000,
              ListPrice: 1000,
              PriceWithoutDiscount: 1000,
              FullSellingPrice: 12000,
              RewardValue: 0,
              PriceValidUntil: "2025-03-11T15:58:30Z",
              AvailableQuantity: 1000000,
              IsAvailable: true,
              Tax: 0,
              DeliverySlaSamples: [
                {
                  DeliverySlaPerTypes: [],
                  Region: null,
                },
              ],
              GetInfoErrorMessage: null,
              CacheVersionUsedToCallCheckout:
                "C8D94BB7955AEF3714DB81F1A4B130EC_",
              PaymentOptions: {
                installmentOptions: [
                  {
                    paymentSystem: "2",
                    bin: null,
                    paymentName: "Visa",
                    paymentGroupName: "creditCardPaymentGroup",
                    value: 1200000,
                    installments: [
                      {
                        count: 1,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 1200000,
                        total: 1200000,
                        sellerMerchantInstallments: [
                          {
                            id: "APIEXAMPLES",
                            count: 1,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 1200000,
                            total: 1200000,
                          },
                        ],
                      },
                    ],
                  },
                  {
                    paymentSystem: "201",
                    bin: null,
                    paymentName: "Promissory",
                    paymentGroupName: "custom201PaymentGroupPaymentGroup",
                    value: 1200000,
                    installments: [
                      {
                        count: 1,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 1200000,
                        total: 1200000,
                        sellerMerchantInstallments: [
                          {
                            id: "APIEXAMPLES",
                            count: 1,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 1200000,
                            total: 1200000,
                          },
                        ],
                      },
                    ],
                  },
                ],
                paymentSystems: [
                  {
                    id: 201,
                    name: "Promissory",
                    groupName: "custom201PaymentGroupPaymentGroup",
                    validator: null,
                    stringId: "201",
                    template: "custom201PaymentGroupPaymentGroup-template",
                    requiresDocument: false,
                    isCustom: true,
                    description: "Promissory Description",
                    requiresAuthentication: false,
                    dueDate: "2024-03-18T15:58:31.1629088Z",
                    availablePayments: null,
                  },
                  {
                    id: 2,
                    name: "Visa",
                    groupName: "creditCardPaymentGroup",
                    validator: null,
                    stringId: "2",
                    template: "creditCardPaymentGroup-template",
                    requiresDocument: false,
                    isCustom: false,
                    description: null,
                    requiresAuthentication: false,
                    dueDate: "2024-03-18T15:57:31.1629088Z",
                    availablePayments: null,
                  },
                ],
                payments: [],
                giftCards: [],
                giftCardMessages: [],
                availableAccounts: [],
                availableTokens: [],
              },
            },
          },
        ],
        Videos: [],
        estimatedDateArrival: null,
      },
    ],
  },
  {
    productId: "39",
    productName: "Whole Watermelon Mini Fresh",
    brand: "Brand",
    brandId: 9280,
    brandImageUrl: null,
    linkText: "whole-watermelon-mini-fresh",
    productReference: "880031",
    productReferenceCode: "880031",
    categoryId: "9282",
    productTitle: "Whole Watermelon Mini Fresh",
    metaTagDescription: "WHOLE WATERMELON MINI FRESH FRUIT PRODUCE VEGETABLES",
    releaseDate: "2020-01-01T00:00:00Z",
    clusterHighlights: {},
    productClusters: {
      "137": "All",
    },
    searchableClusters: {
      "137": "All",
    },
    categories: ["/Food and beverage/"],
    categoriesIds: ["/9282/"],
    link: "https://apiexamples.vtexcommercestable.com.br/whole-watermelon-mini-fresh/p",
    description: "WHOLE WATERMELON MINI FRESH FRUIT PRODUCE VEGETABLES",
    items: [
      {
        itemId: "67",
        name: "Whole Watermelon Mini Fresh",
        nameComplete: "Whole Watermelon Mini Fresh",
        complementName: "WHOLE WATERMELON MINI FRESH FRUIT PRODUCE VEGETABLES",
        ean: "",
        referenceId: [
          {
            Key: "RefId",
            Value: "880310a",
          },
        ],
        measurementUnit: "un",
        unitMultiplier: 1,
        modalType: null,
        isKit: false,
        images: [
          {
            imageId: "155461",
            imageLabel: "whole-watermelon-mini-fresh",
            imageTag:
              '<img src="~/arquivos/ids/155461-#width#-#height#/whole-watermelon-mini-fresh.jpg?v=637534167940100000" width="#width#" height="#height#" alt="whole-watermelon-mini-fresh" id="" />',
            imageUrl:
              "https://apiexamples.vteximg.com.br/arquivos/ids/155461/whole-watermelon-mini-fresh.jpg?v=637534167940100000",
            imageText: "whole-watermelon-mini-fresh",
            imageLastModified: "2021-04-07T18:26:34.0100000Z",
          },
        ],
        sellers: [
          {
            sellerId: "1",
            sellerName: "UNISUPER, SOCIEDAD ANONIMA",
            addToCartLink:
              "https://apiexamples.vtexcommercestable.com.br/checkout/cart/add?sku=67&qty=1&seller=1&sc=1&price=26400&cv=77CDDA620685C6309AA71B868F83D5EA_&sc=1",
            sellerDefault: true,
            commertialOffer: {
              DeliverySlaSamplesPerRegion: {
                "0": {
                  DeliverySlaPerTypes: [],
                  Region: null,
                },
              },
              Installments: [
                {
                  Value: 264,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 264,
                  NumberOfInstallments: 1,
                  PaymentSystemName: "Visa",
                  PaymentSystemGroupName: "creditCardPaymentGroup",
                  Name: "Visa à vista",
                },
                {
                  Value: 264,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 264,
                  NumberOfInstallments: 1,
                  PaymentSystemName: "Promissory",
                  PaymentSystemGroupName: "custom201PaymentGroupPaymentGroup",
                  Name: "Promissory à vista",
                },
              ],
              DiscountHighLight: [],
              GiftSkuIds: [],
              Teasers: [],
              PromotionTeasers: [],
              BuyTogether: [],
              ItemMetadataAttachment: [],
              Price: 264,
              ListPrice: 3000,
              PriceWithoutDiscount: 264,
              FullSellingPrice: 264,
              RewardValue: 0,
              PriceValidUntil: "2025-03-11T15:58:30Z",
              AvailableQuantity: 1000000,
              IsAvailable: true,
              Tax: 0,
              DeliverySlaSamples: [
                {
                  DeliverySlaPerTypes: [],
                  Region: null,
                },
              ],
              GetInfoErrorMessage: null,
              CacheVersionUsedToCallCheckout:
                "77CDDA620685C6309AA71B868F83D5EA_",
              PaymentOptions: {
                installmentOptions: [
                  {
                    paymentSystem: "2",
                    bin: null,
                    paymentName: "Visa",
                    paymentGroupName: "creditCardPaymentGroup",
                    value: 26400,
                    installments: [
                      {
                        count: 1,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 26400,
                        total: 26400,
                        sellerMerchantInstallments: [
                          {
                            id: "APIEXAMPLES",
                            count: 1,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 26400,
                            total: 26400,
                          },
                        ],
                      },
                    ],
                  },
                  {
                    paymentSystem: "201",
                    bin: null,
                    paymentName: "Promissory",
                    paymentGroupName: "custom201PaymentGroupPaymentGroup",
                    value: 26400,
                    installments: [
                      {
                        count: 1,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 26400,
                        total: 26400,
                        sellerMerchantInstallments: [
                          {
                            id: "APIEXAMPLES",
                            count: 1,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 26400,
                            total: 26400,
                          },
                        ],
                      },
                    ],
                  },
                ],
                paymentSystems: [
                  {
                    id: 201,
                    name: "Promissory",
                    groupName: "custom201PaymentGroupPaymentGroup",
                    validator: null,
                    stringId: "201",
                    template: "custom201PaymentGroupPaymentGroup-template",
                    requiresDocument: false,
                    isCustom: true,
                    description: "Promissory Description",
                    requiresAuthentication: false,
                    dueDate: "2024-03-18T15:58:31.1242269Z",
                    availablePayments: null,
                  },
                  {
                    id: 2,
                    name: "Visa",
                    groupName: "creditCardPaymentGroup",
                    validator: null,
                    stringId: "2",
                    template: "creditCardPaymentGroup-template",
                    requiresDocument: false,
                    isCustom: false,
                    description: null,
                    requiresAuthentication: false,
                    dueDate: "2024-03-18T15:57:31.1242269Z",
                    availablePayments: null,
                  },
                ],
                payments: [],
                giftCards: [],
                giftCardMessages: [],
                availableAccounts: [],
                availableTokens: [],
              },
            },
          },
        ],
        Videos: [],
        estimatedDateArrival: null,
      },
    ],
  },
  {
    productId: "38",
    productName: "Fresh Coconuts",
    brand: "Brand",
    brandId: 9280,
    brandImageUrl: null,
    linkText: "fresh-coconuts",
    productReference: "880030",
    productReferenceCode: "880030",
    categoryId: "9282",
    productTitle: "Fresh Coconuts",
    metaTagDescription:
      "Moist and milky, the coconut has a sweet, nutty flavor.",
    releaseDate: "2020-01-01T00:00:00Z",
    clusterHighlights: {},
    productClusters: {
      "137": "All",
      "138": "All",
      "139": "All",
    },
    searchableClusters: {
      "137": "All",
      "138": "All",
      "139": "All",
    },
    categories: ["/Food and beverage/"],
    categoriesIds: ["/9282/"],
    link: "https://apiexamples.vtexcommercestable.com.br/fresh-coconuts/p",
    description: "Moist and milky, the coconut has a sweet, nutty flavor.",
    items: [
      {
        itemId: "66",
        name: "Fresh Coconuts",
        nameComplete: "Fresh Coconuts",
        complementName:
          "Moist and milky, the coconut has a sweet, nutty flavor.",
        ean: "",
        referenceId: [
          {
            Key: "RefId",
            Value: "880300a",
          },
        ],
        measurementUnit: "un",
        unitMultiplier: 1,
        modalType: null,
        isKit: false,
        images: [
          {
            imageId: "155460",
            imageLabel: "fresh-coconuts",
            imageTag:
              '<img src="~/arquivos/ids/155460-#width#-#height#/fresh-coconuts.jpg?v=637534167939970000" width="#width#" height="#height#" alt="fresh-coconuts" id="" />',
            imageUrl:
              "https://apiexamples.vteximg.com.br/arquivos/ids/155460/fresh-coconuts.jpg?v=637534167939970000",
            imageText: "fresh-coconuts",
            imageLastModified: "2021-04-07T18:26:33.9970000Z",
          },
        ],
        sellers: [
          {
            sellerId: "1",
            sellerName: "UNISUPER, SOCIEDAD ANONIMA",
            addToCartLink:
              "https://apiexamples.vtexcommercestable.com.br/checkout/cart/add?sku=66&qty=1&seller=1&sc=1&price=105300&cv=1548F9439AC2C5CBFCC59CA462D6DC56_&sc=1",
            sellerDefault: true,
            commertialOffer: {
              DeliverySlaSamplesPerRegion: {
                "0": {
                  DeliverySlaPerTypes: [],
                  Region: null,
                },
              },
              Installments: [
                {
                  Value: 1053,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 1053,
                  NumberOfInstallments: 1,
                  PaymentSystemName: "Visa",
                  PaymentSystemGroupName: "creditCardPaymentGroup",
                  Name: "Visa à vista",
                },
                {
                  Value: 1053,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 1053,
                  NumberOfInstallments: 1,
                  PaymentSystemName: "Promissory",
                  PaymentSystemGroupName: "custom201PaymentGroupPaymentGroup",
                  Name: "Promissory à vista",
                },
              ],
              DiscountHighLight: [],
              GiftSkuIds: [],
              Teasers: [],
              PromotionTeasers: [],
              BuyTogether: [],
              ItemMetadataAttachment: [],
              Price: 1053,
              ListPrice: 3000,
              PriceWithoutDiscount: 1053,
              FullSellingPrice: 1053,
              RewardValue: 0,
              PriceValidUntil: "2025-03-11T15:58:30Z",
              AvailableQuantity: 1000000,
              IsAvailable: true,
              Tax: 0,
              DeliverySlaSamples: [
                {
                  DeliverySlaPerTypes: [],
                  Region: null,
                },
              ],
              GetInfoErrorMessage: null,
              CacheVersionUsedToCallCheckout:
                "1548F9439AC2C5CBFCC59CA462D6DC56_",
              PaymentOptions: {
                installmentOptions: [
                  {
                    paymentSystem: "2",
                    bin: null,
                    paymentName: "Visa",
                    paymentGroupName: "creditCardPaymentGroup",
                    value: 105300,
                    installments: [
                      {
                        count: 1,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 105300,
                        total: 105300,
                        sellerMerchantInstallments: [
                          {
                            id: "APIEXAMPLES",
                            count: 1,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 105300,
                            total: 105300,
                          },
                        ],
                      },
                    ],
                  },
                  {
                    paymentSystem: "201",
                    bin: null,
                    paymentName: "Promissory",
                    paymentGroupName: "custom201PaymentGroupPaymentGroup",
                    value: 105300,
                    installments: [
                      {
                        count: 1,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 105300,
                        total: 105300,
                        sellerMerchantInstallments: [
                          {
                            id: "APIEXAMPLES",
                            count: 1,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 105300,
                            total: 105300,
                          },
                        ],
                      },
                    ],
                  },
                ],
                paymentSystems: [
                  {
                    id: 201,
                    name: "Promissory",
                    groupName: "custom201PaymentGroupPaymentGroup",
                    validator: null,
                    stringId: "201",
                    template: "custom201PaymentGroupPaymentGroup-template",
                    requiresDocument: false,
                    isCustom: true,
                    description: "Promissory Description",
                    requiresAuthentication: false,
                    dueDate: "2024-03-18T15:58:31.1629088Z",
                    availablePayments: null,
                  },
                  {
                    id: 2,
                    name: "Visa",
                    groupName: "creditCardPaymentGroup",
                    validator: null,
                    stringId: "2",
                    template: "creditCardPaymentGroup-template",
                    requiresDocument: false,
                    isCustom: false,
                    description: null,
                    requiresAuthentication: false,
                    dueDate: "2024-03-18T15:57:31.1629088Z",
                    availablePayments: null,
                  },
                ],
                payments: [],
                giftCards: [],
                giftCardMessages: [],
                availableAccounts: [],
                availableTokens: [],
              },
            },
          },
        ],
        Videos: [],
        estimatedDateArrival: null,
      },
    ],
  },
  {
    productId: "37",
    productName: "Fresh Hass Avocadoes",
    brand: "Brand",
    brandId: 9280,
    brandImageUrl: null,
    linkText: "fresh-hass-avocadoes",
    productReference: "880029",
    productReferenceCode: "880029",
    categoryId: "9282",
    productTitle: "Fresh Hass Avocadoes",
    metaTagDescription: "10 fresh Hass avocados.",
    releaseDate: "2020-01-01T00:00:00Z",
    clusterHighlights: {},
    productClusters: {
      "137": "All",
      "138": "All",
      "139": "All",
    },
    searchableClusters: {
      "137": "All",
      "138": "All",
      "139": "All",
    },
    categories: ["/Food and beverage/"],
    categoriesIds: ["/9282/"],
    link: "https://apiexamples.vtexcommercestable.com.br/fresh-hass-avocadoes/p",
    description: "10 fresh Hass avocados.",
    items: [
      {
        itemId: "65",
        name: "Fresh Hass Avocadoes",
        nameComplete: "Fresh Hass Avocadoes",
        complementName: "10 fresh Hass avocados.",
        ean: "",
        referenceId: [
          {
            Key: "RefId",
            Value: "880290a",
          },
        ],
        measurementUnit: "un",
        unitMultiplier: 1,
        modalType: null,
        isKit: false,
        images: [
          {
            imageId: "155463",
            imageLabel: "fresh-hass-avocadoes",
            imageTag:
              '<img src="~/arquivos/ids/155463-#width#-#height#/fresh-hass-avocadoes.jpg?v=637534167940900000" width="#width#" height="#height#" alt="fresh-hass-avocadoes" id="" />',
            imageUrl:
              "https://apiexamples.vteximg.com.br/arquivos/ids/155463/fresh-hass-avocadoes.jpg?v=637534167940900000",
            imageText: "fresh-hass-avocadoes",
            imageLastModified: "2021-04-07T18:26:34.0900000Z",
          },
        ],
        sellers: [
          {
            sellerId: "1",
            sellerName: "UNISUPER, SOCIEDAD ANONIMA",
            addToCartLink:
              "https://apiexamples.vtexcommercestable.com.br/checkout/cart/add?sku=65&qty=1&seller=1&sc=1&price=29100&cv=05EBB8116CBB0C7965130B328DB9558D_&sc=1",
            sellerDefault: true,
            commertialOffer: {
              DeliverySlaSamplesPerRegion: {
                "0": {
                  DeliverySlaPerTypes: [],
                  Region: null,
                },
              },
              Installments: [
                {
                  Value: 291,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 291,
                  NumberOfInstallments: 1,
                  PaymentSystemName: "Visa",
                  PaymentSystemGroupName: "creditCardPaymentGroup",
                  Name: "Visa à vista",
                },
                {
                  Value: 291,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 291,
                  NumberOfInstallments: 1,
                  PaymentSystemName: "Promissory",
                  PaymentSystemGroupName: "custom201PaymentGroupPaymentGroup",
                  Name: "Promissory à vista",
                },
              ],
              DiscountHighLight: [],
              GiftSkuIds: [],
              Teasers: [],
              PromotionTeasers: [],
              BuyTogether: [],
              ItemMetadataAttachment: [],
              Price: 291,
              ListPrice: 3000,
              PriceWithoutDiscount: 291,
              FullSellingPrice: 291,
              RewardValue: 0,
              PriceValidUntil: "2025-03-11T15:58:30Z",
              AvailableQuantity: 1000000,
              IsAvailable: true,
              Tax: 0,
              DeliverySlaSamples: [
                {
                  DeliverySlaPerTypes: [],
                  Region: null,
                },
              ],
              GetInfoErrorMessage: null,
              CacheVersionUsedToCallCheckout:
                "05EBB8116CBB0C7965130B328DB9558D_",
              PaymentOptions: {
                installmentOptions: [
                  {
                    paymentSystem: "2",
                    bin: null,
                    paymentName: "Visa",
                    paymentGroupName: "creditCardPaymentGroup",
                    value: 29100,
                    installments: [
                      {
                        count: 1,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 29100,
                        total: 29100,
                        sellerMerchantInstallments: [
                          {
                            id: "APIEXAMPLES",
                            count: 1,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 29100,
                            total: 29100,
                          },
                        ],
                      },
                    ],
                  },
                  {
                    paymentSystem: "201",
                    bin: null,
                    paymentName: "Promissory",
                    paymentGroupName: "custom201PaymentGroupPaymentGroup",
                    value: 29100,
                    installments: [
                      {
                        count: 1,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 29100,
                        total: 29100,
                        sellerMerchantInstallments: [
                          {
                            id: "APIEXAMPLES",
                            count: 1,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 29100,
                            total: 29100,
                          },
                        ],
                      },
                    ],
                  },
                ],
                paymentSystems: [
                  {
                    id: 201,
                    name: "Promissory",
                    groupName: "custom201PaymentGroupPaymentGroup",
                    validator: null,
                    stringId: "201",
                    template: "custom201PaymentGroupPaymentGroup-template",
                    requiresDocument: false,
                    isCustom: true,
                    description: "Promissory Description",
                    requiresAuthentication: false,
                    dueDate: "2024-03-18T15:58:31.1543433Z",
                    availablePayments: null,
                  },
                  {
                    id: 2,
                    name: "Visa",
                    groupName: "creditCardPaymentGroup",
                    validator: null,
                    stringId: "2",
                    template: "creditCardPaymentGroup-template",
                    requiresDocument: false,
                    isCustom: false,
                    description: null,
                    requiresAuthentication: false,
                    dueDate: "2024-03-18T15:57:31.1543433Z",
                    availablePayments: null,
                  },
                ],
                payments: [],
                giftCards: [],
                giftCardMessages: [],
                availableAccounts: [],
                availableTokens: [],
              },
            },
          },
        ],
        Videos: [],
        estimatedDateArrival: null,
      },
    ],
  },
  {
    productId: "36",
    productName: "Cauliflower Fresh",
    brand: "Brand",
    brandId: 9280,
    brandImageUrl: null,
    linkText: "cauliflower-fresh",
    productReference: "880027",
    productReferenceCode: "880027",
    categoryId: "9282",
    productTitle: "Cauliflower Fresh",
    metaTagDescription:
      "CAULIFLOWER FRESH PRODUCE FRUIT VEGETABLES EACH BUNDLE",
    releaseDate: "2020-01-01T00:00:00Z",
    clusterHighlights: {},
    productClusters: {
      "137": "All",
    },
    searchableClusters: {
      "137": "All",
    },
    categories: ["/Food and beverage/"],
    categoriesIds: ["/9282/"],
    link: "https://apiexamples.vtexcommercestable.com.br/cauliflower-fresh/p",
    description: "CAULIFLOWER FRESH PRODUCE FRUIT VEGETABLES EACH BUNDLE",
    items: [
      {
        itemId: "64",
        name: "Cauliflower Fresh",
        nameComplete: "Cauliflower Fresh",
        complementName:
          "CAULIFLOWER FRESH PRODUCE FRUIT VEGETABLES EACH BUNDLE",
        ean: "",
        referenceId: [
          {
            Key: "RefId",
            Value: "880270a",
          },
        ],
        measurementUnit: "un",
        unitMultiplier: 1,
        modalType: null,
        isKit: false,
        images: [
          {
            imageId: "155459",
            imageLabel: "cauliflower-fresh",
            imageTag:
              '<img src="~/arquivos/ids/155459-#width#-#height#/cauliflower-fresh.jpg?v=637534167939970000" width="#width#" height="#height#" alt="cauliflower-fresh" id="" />',
            imageUrl:
              "https://apiexamples.vteximg.com.br/arquivos/ids/155459/cauliflower-fresh.jpg?v=637534167939970000",
            imageText: "cauliflower-fresh",
            imageLastModified: "2021-04-07T18:26:33.9970000Z",
          },
        ],
        sellers: [
          {
            sellerId: "1",
            sellerName: "UNISUPER, SOCIEDAD ANONIMA",
            addToCartLink:
              "https://apiexamples.vtexcommercestable.com.br/checkout/cart/add?sku=64&qty=1&seller=1&sc=1&price=29100&cv=535925149F5E5B714E1FDF371AB9FDA4_&sc=1",
            sellerDefault: true,
            commertialOffer: {
              DeliverySlaSamplesPerRegion: {
                "0": {
                  DeliverySlaPerTypes: [],
                  Region: null,
                },
              },
              Installments: [
                {
                  Value: 291,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 291,
                  NumberOfInstallments: 1,
                  PaymentSystemName: "Visa",
                  PaymentSystemGroupName: "creditCardPaymentGroup",
                  Name: "Visa à vista",
                },
                {
                  Value: 291,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 291,
                  NumberOfInstallments: 1,
                  PaymentSystemName: "Promissory",
                  PaymentSystemGroupName: "custom201PaymentGroupPaymentGroup",
                  Name: "Promissory à vista",
                },
              ],
              DiscountHighLight: [],
              GiftSkuIds: [],
              Teasers: [],
              PromotionTeasers: [],
              BuyTogether: [],
              ItemMetadataAttachment: [],
              Price: 291,
              ListPrice: 3000,
              PriceWithoutDiscount: 291,
              FullSellingPrice: 291,
              RewardValue: 0,
              PriceValidUntil: "2025-03-11T15:58:30Z",
              AvailableQuantity: 1000000,
              IsAvailable: true,
              Tax: 0,
              DeliverySlaSamples: [
                {
                  DeliverySlaPerTypes: [],
                  Region: null,
                },
              ],
              GetInfoErrorMessage: null,
              CacheVersionUsedToCallCheckout:
                "535925149F5E5B714E1FDF371AB9FDA4_",
              PaymentOptions: {
                installmentOptions: [
                  {
                    paymentSystem: "2",
                    bin: null,
                    paymentName: "Visa",
                    paymentGroupName: "creditCardPaymentGroup",
                    value: 29100,
                    installments: [
                      {
                        count: 1,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 29100,
                        total: 29100,
                        sellerMerchantInstallments: [
                          {
                            id: "APIEXAMPLES",
                            count: 1,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 29100,
                            total: 29100,
                          },
                        ],
                      },
                    ],
                  },
                  {
                    paymentSystem: "201",
                    bin: null,
                    paymentName: "Promissory",
                    paymentGroupName: "custom201PaymentGroupPaymentGroup",
                    value: 29100,
                    installments: [
                      {
                        count: 1,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 29100,
                        total: 29100,
                        sellerMerchantInstallments: [
                          {
                            id: "APIEXAMPLES",
                            count: 1,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 29100,
                            total: 29100,
                          },
                        ],
                      },
                    ],
                  },
                ],
                paymentSystems: [
                  {
                    id: 201,
                    name: "Promissory",
                    groupName: "custom201PaymentGroupPaymentGroup",
                    validator: null,
                    stringId: "201",
                    template: "custom201PaymentGroupPaymentGroup-template",
                    requiresDocument: false,
                    isCustom: true,
                    description: "Promissory Description",
                    requiresAuthentication: false,
                    dueDate: "2024-03-18T15:58:31.1629088Z",
                    availablePayments: null,
                  },
                  {
                    id: 2,
                    name: "Visa",
                    groupName: "creditCardPaymentGroup",
                    validator: null,
                    stringId: "2",
                    template: "creditCardPaymentGroup-template",
                    requiresDocument: false,
                    isCustom: false,
                    description: null,
                    requiresAuthentication: false,
                    dueDate: "2024-03-18T15:57:31.1629088Z",
                    availablePayments: null,
                  },
                ],
                payments: [],
                giftCards: [],
                giftCardMessages: [],
                availableAccounts: [],
                availableTokens: [],
              },
            },
          },
        ],
        Videos: [],
        estimatedDateArrival: null,
      },
    ],
  },
  {
    productId: "35",
    productName: "Asparagus Green Conventional",
    brand: "Brand",
    brandId: 9280,
    brandImageUrl: null,
    linkText: "asparagus-green-conventional",
    productReference: "880028",
    productReferenceCode: "880028",
    categoryId: "9282",
    productTitle: "Asparagus Green Conventional",
    metaTagDescription: "Asparagus Green Conventional, 1 Bunch",
    releaseDate: "2020-01-01T00:00:00Z",
    clusterHighlights: {},
    productClusters: {
      "137": "All",
    },
    searchableClusters: {
      "137": "All",
    },
    categories: ["/Food and beverage/"],
    categoriesIds: ["/9282/"],
    link: "https://apiexamples.vtexcommercestable.com.br/asparagus-green-conventional/p",
    description: "Asparagus Green Conventional, 1 Bunch",
    items: [
      {
        itemId: "63",
        name: "Asparagus Green Conventional",
        nameComplete: "Asparagus Green Conventional",
        complementName: "Asparagus Green Conventional, 1 Bunch",
        ean: "",
        referenceId: [
          {
            Key: "RefId",
            Value: "880280a",
          },
        ],
        measurementUnit: "un",
        unitMultiplier: 1,
        modalType: null,
        isKit: false,
        images: [
          {
            imageId: "155462",
            imageLabel: "asparagus-green-conventional",
            imageTag:
              '<img src="~/arquivos/ids/155462-#width#-#height#/asparagus-green-conventional.jpg?v=637534167940100000" width="#width#" height="#height#" alt="asparagus-green-conventional" id="" />',
            imageUrl:
              "https://apiexamples.vteximg.com.br/arquivos/ids/155462/asparagus-green-conventional.jpg?v=637534167940100000",
            imageText: "asparagus-green-conventional",
            imageLastModified: "2021-04-07T18:26:34.0100000Z",
          },
        ],
        sellers: [
          {
            sellerId: "1",
            sellerName: "UNISUPER, SOCIEDAD ANONIMA",
            addToCartLink:
              "https://apiexamples.vtexcommercestable.com.br/checkout/cart/add?sku=63&qty=1&seller=1&sc=1&price=25500&cv=B470B6831EBA5CA292C915063FD8B863_&sc=1",
            sellerDefault: true,
            commertialOffer: {
              DeliverySlaSamplesPerRegion: {
                "0": {
                  DeliverySlaPerTypes: [],
                  Region: null,
                },
              },
              Installments: [
                {
                  Value: 255,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 255,
                  NumberOfInstallments: 1,
                  PaymentSystemName: "Visa",
                  PaymentSystemGroupName: "creditCardPaymentGroup",
                  Name: "Visa à vista",
                },
                {
                  Value: 255,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 255,
                  NumberOfInstallments: 1,
                  PaymentSystemName: "Promissory",
                  PaymentSystemGroupName: "custom201PaymentGroupPaymentGroup",
                  Name: "Promissory à vista",
                },
              ],
              DiscountHighLight: [],
              GiftSkuIds: [],
              Teasers: [],
              PromotionTeasers: [],
              BuyTogether: [],
              ItemMetadataAttachment: [],
              Price: 255,
              ListPrice: 3000,
              PriceWithoutDiscount: 255,
              FullSellingPrice: 255,
              RewardValue: 0,
              PriceValidUntil: "2025-03-11T15:58:30Z",
              AvailableQuantity: 1000000,
              IsAvailable: true,
              Tax: 0,
              DeliverySlaSamples: [
                {
                  DeliverySlaPerTypes: [],
                  Region: null,
                },
              ],
              GetInfoErrorMessage: null,
              CacheVersionUsedToCallCheckout:
                "B470B6831EBA5CA292C915063FD8B863_",
              PaymentOptions: {
                installmentOptions: [
                  {
                    paymentSystem: "2",
                    bin: null,
                    paymentName: "Visa",
                    paymentGroupName: "creditCardPaymentGroup",
                    value: 25500,
                    installments: [
                      {
                        count: 1,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 25500,
                        total: 25500,
                        sellerMerchantInstallments: [
                          {
                            id: "APIEXAMPLES",
                            count: 1,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 25500,
                            total: 25500,
                          },
                        ],
                      },
                    ],
                  },
                  {
                    paymentSystem: "201",
                    bin: null,
                    paymentName: "Promissory",
                    paymentGroupName: "custom201PaymentGroupPaymentGroup",
                    value: 25500,
                    installments: [
                      {
                        count: 1,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 25500,
                        total: 25500,
                        sellerMerchantInstallments: [
                          {
                            id: "APIEXAMPLES",
                            count: 1,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 25500,
                            total: 25500,
                          },
                        ],
                      },
                    ],
                  },
                ],
                paymentSystems: [
                  {
                    id: 201,
                    name: "Promissory",
                    groupName: "custom201PaymentGroupPaymentGroup",
                    validator: null,
                    stringId: "201",
                    template: "custom201PaymentGroupPaymentGroup-template",
                    requiresDocument: false,
                    isCustom: true,
                    description: "Promissory Description",
                    requiresAuthentication: false,
                    dueDate: "2024-03-18T15:58:31.1629088Z",
                    availablePayments: null,
                  },
                  {
                    id: 2,
                    name: "Visa",
                    groupName: "creditCardPaymentGroup",
                    validator: null,
                    stringId: "2",
                    template: "creditCardPaymentGroup-template",
                    requiresDocument: false,
                    isCustom: false,
                    description: null,
                    requiresAuthentication: false,
                    dueDate: "2024-03-18T15:57:31.1629088Z",
                    availablePayments: null,
                  },
                ],
                payments: [],
                giftCards: [],
                giftCardMessages: [],
                availableAccounts: [],
                availableTokens: [],
              },
            },
          },
        ],
        Videos: [],
        estimatedDateArrival: null,
      },
    ],
  },
  {
    productId: "34",
    productName: "Yellow Onions (10 lbs.)",
    brand: "Brand",
    brandId: 9280,
    brandImageUrl: null,
    linkText: "yellow-onions",
    productReference: "880026",
    productReferenceCode: "880026",
    categoryId: "9282",
    productTitle: "Yellow Onions (10 lbs.)",
    metaTagDescription:
      'Yellow onions are the go-to onion and can be used whenever a recipe simply calls for "onion." Storing: Onions last for several weeks when kept in a cool, dry, well-ventilated place. After an onion is cut, wrap the extra in plastic wrap and put it in the refrigerator for up to 4 days.',
    releaseDate: "2020-01-01T00:00:00Z",
    clusterHighlights: {},
    productClusters: {
      "137": "All",
    },
    searchableClusters: {
      "137": "All",
    },
    categories: ["/Food and beverage/"],
    categoriesIds: ["/9282/"],
    link: "https://apiexamples.vtexcommercestable.com.br/yellow-onions/p",
    description:
      'Yellow onions are the go-to onion and can be used whenever a recipe simply calls for "onion." Storing: Onions last for several weeks when kept in a cool, dry, well-ventilated place. After an onion is cut, wrap the extra in plastic wrap and put it in the refrigerator for up to 4 days.',
    items: [
      {
        itemId: "62",
        name: "Yellow Onions (10 lbs.)",
        nameComplete: "Yellow Onions (10 lbs.)",
        complementName:
          'Yellow onions are the go-to onion and can be used whenever a recipe simply calls for "onion." Storing: Onions last for several weeks when kept in a cool, dry, well-ventilated place. After an onion is cut, wrap the extra in plastic wrap and put it in the refrigerator for up to 4 days.',
        ean: "",
        referenceId: [
          {
            Key: "RefId",
            Value: "880260a",
          },
        ],
        measurementUnit: "un",
        unitMultiplier: 1,
        modalType: null,
        isKit: false,
        images: [
          {
            imageId: "155458",
            imageLabel: "yellow-onions",
            imageTag:
              '<img src="~/arquivos/ids/155458-#width#-#height#/yellow-onions.jpg?v=637534167939500000" width="#width#" height="#height#" alt="yellow-onions" id="" />',
            imageUrl:
              "https://apiexamples.vteximg.com.br/arquivos/ids/155458/yellow-onions.jpg?v=637534167939500000",
            imageText: "yellow-onions",
            imageLastModified: "2021-04-07T18:26:33.9500000Z",
          },
        ],
        sellers: [
          {
            sellerId: "1",
            sellerName: "UNISUPER, SOCIEDAD ANONIMA",
            addToCartLink:
              "https://apiexamples.vtexcommercestable.com.br/checkout/cart/add?sku=62&qty=1&seller=1&sc=1&price=90700&cv=75AE83858A31D311208028C8FA200338_&sc=1",
            sellerDefault: true,
            commertialOffer: {
              DeliverySlaSamplesPerRegion: {
                "0": {
                  DeliverySlaPerTypes: [],
                  Region: null,
                },
              },
              Installments: [
                {
                  Value: 907,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 907,
                  NumberOfInstallments: 1,
                  PaymentSystemName: "Visa",
                  PaymentSystemGroupName: "creditCardPaymentGroup",
                  Name: "Visa à vista",
                },
                {
                  Value: 907,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 907,
                  NumberOfInstallments: 1,
                  PaymentSystemName: "Promissory",
                  PaymentSystemGroupName: "custom201PaymentGroupPaymentGroup",
                  Name: "Promissory à vista",
                },
              ],
              DiscountHighLight: [],
              GiftSkuIds: [],
              Teasers: [],
              PromotionTeasers: [],
              BuyTogether: [],
              ItemMetadataAttachment: [],
              Price: 907,
              ListPrice: 3000,
              PriceWithoutDiscount: 907,
              FullSellingPrice: 907,
              RewardValue: 0,
              PriceValidUntil: "2025-03-11T15:58:30Z",
              AvailableQuantity: 1000000,
              IsAvailable: true,
              Tax: 0,
              DeliverySlaSamples: [
                {
                  DeliverySlaPerTypes: [],
                  Region: null,
                },
              ],
              GetInfoErrorMessage: null,
              CacheVersionUsedToCallCheckout:
                "75AE83858A31D311208028C8FA200338_",
              PaymentOptions: {
                installmentOptions: [
                  {
                    paymentSystem: "2",
                    bin: null,
                    paymentName: "Visa",
                    paymentGroupName: "creditCardPaymentGroup",
                    value: 90700,
                    installments: [
                      {
                        count: 1,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 90700,
                        total: 90700,
                        sellerMerchantInstallments: [
                          {
                            id: "APIEXAMPLES",
                            count: 1,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 90700,
                            total: 90700,
                          },
                        ],
                      },
                    ],
                  },
                  {
                    paymentSystem: "201",
                    bin: null,
                    paymentName: "Promissory",
                    paymentGroupName: "custom201PaymentGroupPaymentGroup",
                    value: 90700,
                    installments: [
                      {
                        count: 1,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 90700,
                        total: 90700,
                        sellerMerchantInstallments: [
                          {
                            id: "APIEXAMPLES",
                            count: 1,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 90700,
                            total: 90700,
                          },
                        ],
                      },
                    ],
                  },
                ],
                paymentSystems: [
                  {
                    id: 201,
                    name: "Promissory",
                    groupName: "custom201PaymentGroupPaymentGroup",
                    validator: null,
                    stringId: "201",
                    template: "custom201PaymentGroupPaymentGroup-template",
                    requiresDocument: false,
                    isCustom: true,
                    description: "Promissory Description",
                    requiresAuthentication: false,
                    dueDate: "2024-03-18T15:58:31.1657752Z",
                    availablePayments: null,
                  },
                  {
                    id: 2,
                    name: "Visa",
                    groupName: "creditCardPaymentGroup",
                    validator: null,
                    stringId: "2",
                    template: "creditCardPaymentGroup-template",
                    requiresDocument: false,
                    isCustom: false,
                    description: null,
                    requiresAuthentication: false,
                    dueDate: "2024-03-18T15:57:31.1657752Z",
                    availablePayments: null,
                  },
                ],
                payments: [],
                giftCards: [],
                giftCardMessages: [],
                availableAccounts: [],
                availableTokens: [],
              },
            },
          },
        ],
        Videos: [],
        estimatedDateArrival: null,
      },
    ],
  },
  {
    productId: "1",
    productName: "Catalog API",
    brand: "Test Brand name",
    brandId: 2000000,
    brandImageUrl: null,
    linkText: "catalog-api",
    productReference: "4321",
    productReferenceCode: "4321",
    categoryId: "1",
    productTitle: "Catalog API",
    metaTagDescription: "Catalog API",
    releaseDate: "2021-08-17T00:00:00Z",
    clusterHighlights: {
      "140": "Coleção teste da Karen e do Bruno",
    },
    productClusters: {
      "140": "Coleção teste da Karen e do Bruno",
    },
    searchableClusters: {
      "140": "Coleção teste da Karen e do Bruno",
    },
    categories: ["/Test Category/"],
    categoriesIds: ["/1/"],
    link: "https://apiexamples.vtexcommercestable.com.br/catalog-api/p",
    description: "Catalog API",
    items: [
      {
        itemId: "1",
        name: "sku1",
        nameComplete: "Catalog API sku1",
        complementName: "",
        ean: "5999988874155",
        referenceId: [
          {
            Key: "RefId",
            Value: "9870",
          },
        ],
        measurementUnit: "un",
        unitMultiplier: 1,
        modalType: null,
        isKit: false,
        images: [
          {
            imageId: "155467",
            imageLabel: "label",
            imageTag:
              '<img src="~/arquivos/ids/155467-#width#-#height#/Water-bottle.jpg?v=637711423456830000" width="#width#" height="#height#" alt="" id="" />',
            imageUrl:
              "https://apiexamples.vteximg.com.br/arquivos/ids/155467/Water-bottle.jpg?v=637711423456830000",
            imageText: null,
            imageLastModified: "2021-10-29T22:12:25.6830000Z",
          },
          {
            imageId: "155397",
            imageLabel: "label",
            imageTag:
              '<img src="~/arquivos/ids/155397-#width#-#height#/Water-bottle.jpg?v=637431343477370000" width="#width#" height="#height#" alt="" id="" />',
            imageUrl:
              "https://apiexamples.vteximg.com.br/arquivos/ids/155397/Water-bottle.jpg?v=637431343477370000",
            imageText: null,
            imageLastModified: "2020-12-09T18:12:27.7370000Z",
          },
          {
            imageId: "155468",
            imageLabel: "label",
            imageTag:
              '<img src="~/arquivos/ids/155468-#width#-#height#/Water-bottle.jpg?v=637711424499430000" width="#width#" height="#height#" alt="" id="" />',
            imageUrl:
              "https://apiexamples.vteximg.com.br/arquivos/ids/155468/Water-bottle.jpg?v=637711424499430000",
            imageText: null,
            imageLastModified: "2021-10-29T22:14:09.9430000Z",
          },
          {
            imageId: "155469",
            imageLabel: null,
            imageTag:
              '<img src="~/arquivos/ids/155469-#width#-#height#/20210226151140-vtex_logosvg.png?v=637832108876400000" width="#width#" height="#height#" alt="" id="" />',
            imageUrl:
              "https://apiexamples.vteximg.com.br/arquivos/ids/155469/20210226151140-vtex_logosvg.png?v=637832108876400000",
            imageText: null,
            imageLastModified: "2022-03-18T14:34:47.6400000Z",
          },
        ],
        sellers: [
          {
            sellerId: "1",
            sellerName: "UNISUPER, SOCIEDAD ANONIMA",
            addToCartLink:
              "https://apiexamples.vtexcommercestable.com.br/checkout/cart/add?sku=1&qty=1&seller=1&sc=1&price=10000&cv=DC191C9A7CD44DE1A7186B1C8BCB28DA_&sc=1",
            sellerDefault: true,
            commertialOffer: {
              DeliverySlaSamplesPerRegion: {},
              Installments: [],
              DiscountHighLight: [],
              GiftSkuIds: [],
              Teasers: [],
              PromotionTeasers: [],
              BuyTogether: [],
              ItemMetadataAttachment: [],
              Price: 100,
              ListPrice: 100,
              PriceWithoutDiscount: 100,
              FullSellingPrice: 100,
              RewardValue: 0,
              PriceValidUntil: "2025-03-11T15:58:30Z",
              AvailableQuantity: 0,
              IsAvailable: false,
              Tax: 0,
              DeliverySlaSamples: [],
              GetInfoErrorMessage:
                "Code: withoutStock Status:error Message: The item Catalog API sku1 has no inventory",
              CacheVersionUsedToCallCheckout:
                "DC191C9A7CD44DE1A7186B1C8BCB28DA_",
              PaymentOptions: {
                installmentOptions: [],
                paymentSystems: [],
                payments: [],
                giftCards: [],
                giftCardMessages: [],
                availableAccounts: [],
                availableTokens: [],
              },
            },
          },
        ],
        Videos: [],
        estimatedDateArrival: null,
      },
    ],
  },
];
